# Page 176

In [4]:
import numpy as np

# Define the Jacobian matrix J
J = np.array([
    [20, 0, 0, 0, 0, 0],
    [-7, 0, 1, 0, 0, 0],
    [0, 15, 0, 0, 0, 0],
    [0, 1, 0, 0, 1, 0],
    [0, 0, 0, 1, 0, 0],
    [1, 0, 0, 0, 0, 1]
])

# Define the joint differential motions Dθ
D_theta = np.array([
    [0],
    [0.1],
    [0],
    [-0.1],
    [0.05],
    [0.03]
])

In [6]:
# Calculate the differential motions D = J * Dθ
D = np.dot(J, D_theta)

# Output the result
D

array([[ 0.  ],
       [ 0.  ],
       [ 1.5 ],
       [ 0.15],
       [-0.1 ],
       [ 0.03]])

In [7]:
J @ D_theta

array([[ 0.  ],
       [ 0.  ],
       [ 1.5 ],
       [ 0.15],
       [-0.1 ],
       [ 0.03]])

# 5.6.4 Differential Transformations of a Frame

In [8]:
import numpy as np

# Define the differential operator matrix
delta = np.array([
    [0, -0.06, 0, 0.04, 0.05],
    [0, 0.06, 0, -0.02, 0.03],
    [-0.04, 0, 0.02, 0, 0.01],
    [0, 0, 0, 0, 0]
])

# Print the matrix
print("Differential Operator Matrix (Δ):")
print(delta)


Differential Operator Matrix (Δ):
[[ 0.   -0.06  0.    0.04  0.05]
 [ 0.    0.06  0.   -0.02  0.03]
 [-0.04  0.    0.02  0.    0.01]
 [ 0.    0.    0.    0.    0.  ]]


# Example 5.5
- Pre-multiplying the frame with the differential operator

In [10]:
B = np.array([
    [0, 0, 1, 8],
    [1, 0, 0, 2],
    [0, 1, 0, 3],
    [0, 0, 0, 1]
])

In [14]:
delta = np.array([
    [0,     0, 0.01,    0.03],
    [0,     0, 0,       0.04],
    [-0.01, 0, 0,       0],
    [0,     0, 0,       0]
])

In [17]:
delta @ B

array([[ 0.  ,  0.01,  0.  ,  0.06],
       [ 0.  ,  0.  ,  0.  ,  0.04],
       [ 0.  ,  0.  , -0.01, -0.08],
       [ 0.  ,  0.  ,  0.  ,  0.  ]])

In [19]:
np.dot(delta, B)

array([[ 0.  ,  0.01,  0.  ,  0.06],
       [ 0.  ,  0.  ,  0.  ,  0.04],
       [ 0.  ,  0.  , -0.01, -0.08],
       [ 0.  ,  0.  ,  0.  ,  0.  ]])