# Appendix A
# A.1 Matrix Algebra and Notation: A Review

- A Matrix is a collection of ***m*** columns and ***n*** rows
- Dimensions are ***m x n***
- Each element is referred to as ***A<sub>ij</sub>***
- A Matrix with the same number of columns and rows is called a ***Square Matrix***

# Matrix Transpose
- The transpose of a Matrix results in another Matrix where the elements are swapped from row to column, or the other way around

In [1]:
import numpy as np 

In [3]:
A = np.array([
    [1,2,3],
    [4,5,6]]
)
A

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
np.transpose(A)

array([[1, 4],
       [2, 5],
       [3, 6]])

# Matrix Multiplication

# Diagonal Matrix

# Matrix Addition

# Determinant of a Matrix

In [6]:
A = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]]
)
np.linalg.det(A)

-9.51619735392994e-16

# Matrix Inversion

- Important operation in Matrix representation in robots. 
- Used for both Inverse Kinematics and Differential Motions
- Two general purpose inversion techniques are mentioned for square matrices
- 

In [8]:
import numpy as np
A = np.array([
    [1, 2, 3],  # Corresponds to d, e, f
    [4, 5, 6]   # Corresponds to g, h, l
])
B = np.array([
    [7, 8],    # Corresponds to p, s
    [9, 10],   # Corresponds to q, t
    [11, 12]   # Corresponds to r, w
])
C = np.dot(A, B)

print("Matrix A:")
print(A)
print("\nMatrix B:")
print(B)
print("\nMatrix C = A * B:")
print(C)

C = np.dot(B, A)

print("Matrix A:")
print(A)
print("\nMatrix B:")
print(B)
print("\nMatrix C = A * B:")
print(C)


Matrix A:
[[1 2 3]
 [4 5 6]]

Matrix B:
[[ 7  8]
 [ 9 10]
 [11 12]]

Matrix C = A * B:
[[ 58  64]
 [139 154]]
Matrix A:
[[1 2 3]
 [4 5 6]]

Matrix B:
[[ 7  8]
 [ 9 10]
 [11 12]]

Matrix C = A * B:
[[ 39  54  69]
 [ 49  68  87]
 [ 59  82 105]]
