# 2. Kinematics of Serial Robots: Position Analysis

# 2.2 Robots as Mechanisms

# 2.4.1 Representation of a Point in Space

- i, j and k are unit vectors.
- These vectors usually represent x, y and z cartesian coordinates 
- The Point can be represented as a vector in "vector form"
  - P = 3i + 5j + 2k
- 3i means you are moving 3 units along the x axis
- If the units are in meters, then we are moving 3 meters long the x axis
  - i is the unit vector in the x direction. It has a magnitude of 1 and points along the positive x axis
  - j is the unit vector in the y direction. It has a magnitude of 1 and points along the positive y axis
  - k is the unit vector in the z direction. It has a magnitude of 1 and points along the positive z axis
- So for the above vector:
  - 3i means move 3 units along the x axis
  - This is a formula rather than an equation
    - It provides a way to calculate the position vector P
    - An equation states that two expressions are equal

# 2.4.2 Representation of a Vector in Space

- The below code demonstrates how to calculate a vector and its magnitude 
- We are subtracting the coordinates of the starting point from the coordinates of the ending point

In [42]:
import numpy as np

# A = np.array([1, 2, 3])

A = np.array([0, 0, 0])
B = np.array([4, 6, 8])
P_AB = B - A

print(f"Vector P_AB = {P_AB[0]}i + {P_AB[1]}j + {P_AB[2]}k")


Vector P_AB = 4i + 6j + 8k


- Direction Vector
- When the scale component w is zero
- Converting from Matrix to Cartesian (I think?)
- We divide each component by the weight
- If Px, Py and Pz are divided by w then we get Ax, Ay, Az

In [48]:
np.array([2,3,4]) / 0
np.array([2,3,4]) / 1
np.array([2,3,4]) / 2



C:\Users\James\AppData\Local\Temp\ipykernel_25300\559588662.py:1: RuntimeWarning: divide by zero encountered in divide
  np.array([2,3,4]) / 0


array([1. , 1.5, 2. ])

Example 2.1
- A vector is described as P = 3i + 5j + 2k, express it as matrix form:
1. With a scale factor of 2
2. If it were to describe a direction as a unit vector

In [1]:
import numpy as np
import math

In [2]:
P = np.array([3,5,2])
P * 2

array([ 6, 10,  4])

Converting a Vector into a Unit Vector
- Normalize the length (magnitude) to be equal to 1.
- Each component (element) is divided by the "square root of the sum of the squares of all (three) components"
1. Square each component
2. Add the squares together
3. Find the square root of the sum
4. Divide each of the components by this sum

In [49]:
sq_Sum = math.sqrt(3**2 + 5**2 + 2**2)
sq_Sum

6.164414002968976

In [58]:
UnitV = P / sq_Sum
UnitV

array([0.48666426, 0.81110711, 0.32444284])

In [59]:
math.sqrt(UnitV[0]**2 + UnitV[1]**2 + UnitV[2]**2)

1.0

Example 2.2
- A Vector P is 5 units long and is in the direction of unit vector q described as follows:
- Express the vector in matrix form:

In [60]:
q = None
q_unit = np.array([0.371, 0.557, q])

In [63]:
q = math.sqrt(1 - (0.371**2 + 0.557**2))
q

0.7430410486642041

In [64]:
q_unit = np.array([0.371, 0.557, q])
q_unit * 5

array([1.855     , 2.785     , 3.71520524])

# 2.4.3 Representation of a Frame at the Origin of a Fixed Reference Frame

# 2.4.4 Representation of a Frame Relative to a Fixed Reference Frame

- A frame can be expressed by it's three "directional vectors" and it's single "position vector"
- The frame is expressed by it's three vectors describing it's directional "unit vectors" and a fourth vector describing it's location
- So we have 9 pieces of information for the frame's orientation - 3x3 matrix
- And we have 3 pieces of information for the frames's position - x,y and z vector

Example 2.3

In [24]:
degree = 45
math.radians(degree)
np.sqrt(2) / 2
math.sin(math.radians(degree))

0.7071067811865476

In [27]:
print("x_Axis_Rotation Matrix")
degree = 45
np.array([
    [1, 0, 0, 0],
    [0, math.cos(math.radians(degree)), -math.sin(math.radians(degree)), 0],
    [0, math.sin(math.radians(degree)), math.cos(math.radians(degree)), 0],
    [0, 0, 0, 1]
])

x_Axis_Rotation Matrix


array([[ 1.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.70710678, -0.70710678,  0.        ],
       [ 0.        ,  0.70710678,  0.70710678,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  1.        ]])

In [30]:
print("y_Axis_Rotation Matrix")
degree = 45
np.array([
    [math.cos(math.radians(degree)), 0, math.sin(math.radians(degree)), 0],
    [0, 1, 0, 0],
    [-math.sin(math.radians(degree)), 0, math.cos(math.radians(degree)), 0],
    [0, 0, 0, 1]
])

y_Axis_Rotation Matrix


array([[ 0.70710678,  0.        ,  0.70710678,  0.        ],
       [ 0.        ,  1.        ,  0.        ,  0.        ],
       [-0.70710678,  0.        ,  0.70710678,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  1.        ]])

In [31]:
print("z_Axis_Rotation Matrix")
degree = 45
np.array([
    [math.cos(math.radians(degree)), -math.sin(math.radians(degree)), 0, 0],
    [math.sin(math.radians(degree)), math.cos(math.radians(degree)), 0, 0],
    [0, 0, 1, 0],
    [0, 0, 0, 1]
])

z_Axis_Rotation Matrix


array([[ 0.70710678, -0.70710678,  0.        ,  0.        ],
       [ 0.70710678,  0.70710678,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  1.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  1.        ]])

# 2.4.5 Representation of a Rigid Body

In [34]:
print("As before, a frame can be represented by a matrix, where the origin of the frame and the three vectors representing its orientation relative to the reference frame are expressed")

np.array([
    ["nx", "ox", "ax", "px"],
    ["ny", "oy", "ay", "py"],
    ["nz", "oz", "az", "pz"],
    [0, 0, 0, "w"]
])

As before, a frame can be represented by a matrix, where the origin of the frame and the three vectors representing its orientation relative to the reference frame are expressed


array([['nx', 'ox', 'ax', 'px'],
       ['ny', 'oy', 'ay', 'py'],
       ['nz', 'oz', 'az', 'pz'],
       ['0', '0', '0', 'w']], dtype='<U11')

- A point in space only has three DOF, it can only move along the x,y and z axis
- A rigid body in space has six DOF, it can move along the x,y and z axis and also rotate and spin on these three axis as well
- All that is needed to full describe a rigid body in space is 6 pieces of information
- However, in the matrix we have 12 pieces of information:
  - We have a 3x3 matrix - so 9 pieces of information
  - Plus a vector of 3 components - so another 3 pieces of information
  - Excluding the scale factors on the last row
- So we need "six constraint equations" to reduce the pieces of information from 12 to 6

# The Constraint Equations

The Constraint Equations come from known characteristics of a frame; they are:  
1. The three unit vectors n,o and a are mutually perpendicular
2. Each unit vector representing directional cosines must be equal to 1

These constraints translate into the following six constraint equations:  

Dot Products must equal ZERO (Remember $\cdot$ and 0 are similar signs)
- n $\cdot$ o = |n| * |o| * cos(theta) = 0 (the dot product (result is a scalar) of n and o must be zero)
- n $\cdot$ a = 0
- a $\cdot$ o = 0

Unit Vectors must equal ONE (Remember 1 and | are similar signs)
- |n| = √(Nx<sup>2</sup> + Ny<sup>2</sup> + Nz<sup>2</sup>) = 1 (the magnitude of the length of the vector must be 1 eg: Unit Vector)
- |o| = 1 
- |a| = 1


We use Pythagoras Theorem to calculate the magnitude: |n| = √(x<sup>2</sup> + y<sup>2</sup>)

- The values in a frame must satisfy the above equations, otherwise the frame is incorrect
- Note the dot product is a scalar, not a vector
- So to ensure the right-hand rule is followed, we can instead use the Cross Product method:  
  

<div style="text-align: center;font-weight: bold">
n x o = a   
</div>  


- It is recommended that the Cross Product equation be used as it determines the correct relationship among the three vectors

Example 2.4

- Find the values of the missing components in the below frame
- The vector 5,3,2 is the position of the origin of the frame and does not affect the Constraint Equations
- Note that only three values for the directional vectors are given, this is all that is needed
- We then use the Six Constraint Equations from above

In [37]:
np.array([
    ["?",    0,     "?",    5],
    [0.707, "?",    "?",    3],
    ["?",   "?",    0,      2],
    [0,     0,      0,      1]
])
np.array([
    [None,      0,       None,    5],
    [0.707,     None,    None,    3],
    [None,      None,    0,       2],
    [0,         0,       0,       1]
])

array([[None, 0, None, 5],
       [0.707, None, None, 3],
       [None, None, 0, 2],
       [0, 0, 0, 1]], dtype=object)

# Dot Product
Ways to calculate the dot product (answer is a scalar and is zero)

1. Using the magnitudes and Cosines of the angle:  
n $\cdot$ o = |n| $\cdot$ |o| $\cdot$ cos(theta) = 0

2. Using the Component-wise Multiplication  
n $\cdot$ o = (n<sub>x</sub>  $\cdot$  o<sub>x</sub>) + (n<sub>y</sub>  $\cdot$  o<sub>y</sub>) + (n<sub>z</sub>  $\cdot$  o<sub>z</sub>) = 0  

- However, the problem is that it's possible to have two sets of mutually perpendicular vectors in opposite directions. Meaning we get two frames ref page 44 - F1 and F1.


# Cross Product - **n x o = a**
Calculating the Cross Product (think cross for multiplication)  
The result is a a third vector that is perpendicular to the plane formed by the original two vectors  
We then have a frame that applies the right-hand rule and is correct    

Figure 2.12

In [67]:
# Define the vectors n and o
n = np.array([2, 3, 4])
o = np.array([5, 6, 7])

# Calculate the cross product
np.cross(n, o)

array([-3,  6, -3])

Example 2.5

Steps to solve missing components in a matrix that is already converted to a Unit Vector:  
1. Solve the Unit Vectors (the vector's magnitude must equal 1)
   1. Note that the vector is already a Unit Vector. So there is no Square Root radical, the vector has already been normalized to 1.
2. Solve the Dot Product (the result from vector N and vector O must be a scalar and equal 0)
3. Solve the Cross Product (the result must be a third vector which is vector A)

In [75]:
N = np.array([0.866, 0.5, 0])
O = np.array([0, 0, 1])
np.cross(N,O)

array([ 0.5  , -0.866,  0.   ])

In [ ]:
# i (Ny * Oz - Nz * Oy)


In [70]:
Nx = None
Oy = None
Oz = None
Ax = None
Ay = None
Ax = None

np.array([
    [Nx,        0,       Ax,    3],
    [0.5,       Oy,      Ay,    9],
    [0,         Oz,      Ax,    7],
    [0,         0,       0,     1]
])

array([[None, 0, None, 3],
       [0.5, None, None, 9],
       [0, None, None, 7],
       [0, 0, 0, 1]], dtype=object)

# 2.5 Homogeneous Transformation Matrices

- Meaning a 4x4 matrix
- A standard for multiplying matrices because they are the same size, also known as the same dimensions

# 2.6 Representation of Transformations

- A transformation is defined as making a movement in space
- When a frame (a vector, object or a moving frame) moves in space relative to a fixed reference frame, we represent this motion in a form similar to a frame representation
- This is because a transformation is a change in the state of frame
- A transformation may be in one of the following forms:
1. A pure translation
2. A pure rotation about an axis
3. A combination of translation and rotation 

# 2.6.1 Representation of a Pure Translation
- When a point, vector or object moves in space without any rotation
- The direction unit vectors remain unchanged 
- Only the origin of the frame relative to the reference frame changes

In [76]:
F = np.array([
    [0.527,     -0.574, 0.628,  8],
    [0.369,     0.819,  0.439,  10],
    [-0.766,    0,      0.643,  6],
    [0,         0,      0,      1]
])

T = np.array([
    [1,0,0,3],
    [0,1,0,0],
    [0,0,1,2],
    [0,0,0,1]
])

T @ F

array([[ 0.527, -0.574,  0.628, 11.   ],
       [ 0.369,  0.819,  0.439, 10.   ],
       [-0.766,  0.   ,  0.643,  8.   ],
       [ 0.   ,  0.   ,  0.   ,  1.   ]])

# 2.6.2 Representation of a Pure Rotation about an Axis

- The example explains a reference frame x,y,z and a rotating frame n,o,a
- There is also a point P attached to the rotation frame
- As the rotating frame moves, point P remains in the same coordinate position of the rotating frame
- However, relative to the reference frame, point P changes it's x,y,z coordinates